-- seed-embedding-verification.sql
--
-- Purpose: insert ONE minimal `components` fixture row that has no embedding, so
-- `get_missing_usage_embedding_items()` has something real to find when verifying the
-- embedding backfill cron (see ops/README-embedding-cron.md).
--
-- IDEMPOTENT: guarded by `ON CONFLICT (user_id, component_slug) DO NOTHING`, so re-running
-- this file is a no-op. INSERT-only; it never updates or deletes an existing row.
--
-- NOT APPLIED BY ANY AGENT. Applying this against the live database requires explicit
-- user approval (Phase 3 Step D4 hard stop). Review the statement before running it.
--
-- EMPTY-DATABASE EDGE CASE: `user_id` is resolved with a subquery against `public.users`.
-- The `INSERT ... SELECT ... FROM public.users LIMIT 1` form means that if the database has
-- zero users, the SELECT yields zero rows and the INSERT is a clean no-op (0 rows inserted)
-- rather than a NOT NULL / FK violation. Seed a user first if you need the fixture.
--
-- ---------------------------------------------------------------------------
-- COLUMN SHAPE (`components`, @@unique([user_id, component_slug]))
-- Source: ops/seed-placeholder-components.mjs schema recon, from apps/web/prisma/schema.prisma
--   id                Int     PK autoincrement       -- DB-assigned, do not set
--   user_id           String  NOT NULL, FK users.id  -- resolved via subquery below
--   component_slug    String  NOT NULL, unique w/ user_id
--   name              String  NOT NULL               -- slug-style machine name
--   component_names   Json    NOT NULL, no default   -- array of display names
--   preview_url       String  NOT NULL, NO DEFAULT   -- must be set; NULL breaks the insert
--   code              String  default 'N/A'          -- nullable-in-effect, omitted
--   description       String? nullable               -- omitted
--   fts               tsvector generated by DB       -- do NOT set
--   is_public         Boolean default true           -- set false here (see note)
--
-- `is_public = false` keeps this fixture out of the public marketplace UI and is SAFE for the
-- verification purpose: get_missing_usage_embedding_items() (supabase/migrations/0001_embedding_functions.sql)
-- selects every `components` row with no matching usage_embeddings row and applies NO is_public
-- filter, so a private fixture is still found.
-- ---------------------------------------------------------------------------

INSERT INTO public.components (
  user_id,
  component_slug,
  name,
  component_names,
  preview_url,
  description,
  is_public
)
SELECT
  u.id,
  'embedding-verification-fixture',
  'embedding-verification-fixture',
  -- Untyped literal on purpose: coerces to whichever of json/jsonb the column actually is.
  '["Embedding Verification Fixture"]',
  'https://placehold.co/1200x900/png',
  'Non-user-facing fixture row used to verify the embedding backfill cron finds missing items.',
  false
FROM public.users AS u
LIMIT 1
ON CONFLICT (user_id, component_slug) DO NOTHING;

-- Verification query (read-only) — should return the fixture once applied:
--
--   SELECT id, user_id, component_slug
--   FROM public.components
--   WHERE component_slug = 'embedding-verification-fixture';
--
-- And it should then appear in:
--
--   SELECT * FROM get_missing_usage_embedding_items();
