import { FormField } from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { cn } from "@/lib/utils"
import { useUser } from "@clerk/nextjs"
import { ChangeEvent, useEffect, useId } from "react"
import { UseFormReturn, useController } from "react-hook-form"
import { SandboxStatus } from "../../../sandbox/hooks/use-sandbox"
import { FormData } from "../../config/utils"
import { useSubmitFormHotkeys } from "../../hooks/use-hooks"
import { makeSlugFromName, useIsCheckSlugAvailable } from "../../hooks/use-is-check-slug-available"
import { usePrefillAutogeneratedSlug } from "../../hooks/use-name-slug-form"
import { CheckCircle2, XCircle, Loader2 } from "lucide-react"

export const ComponentForm = ({
  form,
  status,
  handleSubmit,
  hotkeysEnabled = true,
  isSlugReadOnly = true,
  publishAsUserId,
  showOptionalFields = true,
  placeholderName = "",
  isFirstStep = false,
}: {
  form: UseFormReturn<FormData>
  status: SandboxStatus
  handleSubmit?: (event: React.FormEvent) => void
  isSubmitting?: boolean
  hotkeysEnabled?: boolean
  isSlugReadOnly?: boolean
  publishAsUserId?: string
  showOptionalFields?: boolean
  placeholderName?: string
  isFirstStep?: boolean
}) => {
  const { user: currentUser } = useUser()
  const userId = publishAsUserId ?? currentUser?.id

  usePrefillAutogeneratedSlug({
    form,
    publishAsUserId: userId,
    status,
  })

  if (handleSubmit) {
    useSubmitFormHotkeys(form, handleSubmit, hotkeysEnabled)
  }

  const nameId = useId()
  const slugId = useId()
  const descriptionId = useId()
  const registryId = useId()
  const defaultRows = 2

  const handleTextareaInput = (e: ChangeEvent<HTMLTextAreaElement>) => {
    const textarea = e.target
    textarea.style.height = "auto"

    const style = window.getComputedStyle(textarea)
    const borderHeight =
      parseInt(style.borderTopWidth) + parseInt(style.borderBottomWidth)

    const newHeight = textarea.scrollHeight + borderHeight

    textarea.style.height = `${newHeight}px`
  }

  const { field: nameField } = useController({
    name: "name",
    control: form.control,
    rules: { required: true },
  })

  useEffect(() => {
    if (nameField.value) {
      const newSlug = makeSlugFromName(nameField.value)
      form.setValue("component_slug", newSlug)
    }
  }, [nameField.value, form])

  const currentSlug = form.watch("component_slug")
  const { isSlugAvailable, isCheckingSlug } = useIsCheckSlugAvailable({
    slug: currentSlug,
  })

  return (
    <div className="flex flex-col gap-4 w-full">
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label htmlFor={nameId}>
            Name <span className="text-destructive">*</span>
          </Label>
          <Input
            id={nameId}
            ref={nameField.ref}
            placeholder={`e.g. "${(placeholderName || "Button").replace(/([a-z])([A-Z])/g, "$1 $2")}"`}
            value={nameField.value}
            disabled={status !== "draft"}
            onChange={nameField.onChange}
            onBlur={nameField.onBlur}
            className="w-full text-foreground"
            required
          />
          <p
            className="text-xs text-muted-foreground"
            role="region"
            aria-live="polite"
          >
            The display name of your component
          </p>
          {form.formState.errors.name && (
            <p className="text-xs text-destructive mt-1">
              {form.formState.errors.name.message}
            </p>
          )}
        </div>

        <div className="space-y-2">
          <Label htmlFor={slugId}>
            Slug <span className="text-destructive">*</span>
          </Label>
          <div className="relative">
            <Input
              id={slugId}
              {...form.register("component_slug", { required: true })}
              className="w-full pr-10"
              placeholder={`e.g. "${makeSlugFromName(placeholderName || "Button")}"`}
              disabled={true}
              required
            />
            {currentSlug && (
              <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center justify-center">
                {isCheckingSlug ? (
                  <Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />
                ) : isSlugAvailable === false ? (
                  <XCircle className="w-4 h-4 text-destructive" />
                ) : isSlugAvailable === true ? (
                  <CheckCircle2 className="w-4 h-4 text-green-500" />
                ) : null}
              </div>
            )}
          </div>
          <div className="flex items-center justify-between mt-1">
            <p
              className="text-xs text-muted-foreground"
              role="region"
              aria-live="polite"
            >
              Used in the URL and imports, can't be changed later
            </p>
            {currentSlug && isSlugAvailable === true && !isCheckingSlug && (
              <span className="text-xs text-green-500 font-medium">This slug is available</span>
            )}
            {currentSlug && isSlugAvailable === false && !isCheckingSlug && (
              <span className="text-xs text-destructive font-medium">This slug is already taken</span>
            )}
          </div>
          {form.formState.errors.component_slug && (
            <p className="text-xs text-destructive mt-1">
              {form.formState.errors.component_slug.message}
            </p>
          )}
        </div>
      </div>
      
      <div className="space-y-3">
        <Label>
          Type <span className="text-destructive">*</span>
        </Label>
        <div className="flex p-1 bg-muted/50 rounded-lg w-fit border border-border/50">
          {["UI", "Hook", "Block", "Icon"].map((type) => {
            const value = type.toLowerCase()
            const isActive = form.watch("registry") === value
            return (
              <button
                key={type}
                type="button"
                onClick={() => form.setValue("registry", value, { shouldValidate: true })}
                className={cn(
                  "px-4 py-1.5 text-sm font-medium rounded-md transition-all",
                  isActive
                    ? "bg-background text-foreground shadow-sm ring-1 ring-border"
                    : "text-muted-foreground hover:text-foreground hover:bg-muted"
                )}
              >
                {type}
              </button>
            )
          })}
        </div>
      </div>
      {showOptionalFields && (
        <div className="space-y-6">
          <div
            className={cn(
              "grid gap-4",
              isFirstStep ? "grid-cols-2" : "grid-cols-1",
            )}
          >
            <div className="space-y-2">
              <Label htmlFor={descriptionId}>
                Description <span className="text-destructive">*</span>
              </Label>
              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <Textarea
                    id={descriptionId}
                    placeholder="Add some description to help others discover your component"
                    className={cn(
                      "min-h-[none] resize-none",
                      form.formState.errors.description && "border-destructive",
                    )}
                    rows={defaultRows}
                    required
                    {...field}
                    onChange={(e) => {
                      field.onChange(e)
                      handleTextareaInput(e)
                    }}
                    ref={(e) => {
                      if (e) {
                        const style = window.getComputedStyle(e)
                        const lineHeight = parseInt(style.lineHeight)
                        const borderHeight =
                          parseInt(style.borderTopWidth) +
                          parseInt(style.borderBottomWidth)
                        const paddingHeight =
                          parseInt(style.paddingTop) +
                          parseInt(style.paddingBottom)
                        const initialHeight =
                          lineHeight * defaultRows +
                          borderHeight +
                          paddingHeight
                        e.style.height = `${initialHeight}px`
                      }
                    }}
                  />
                )}
              />
              <p
                className="text-xs text-muted-foreground"
                role="region"
                aria-live="polite"
              >
                A brief description of what your component does
              </p>
              {form.formState.errors.description && (
                <p className="text-xs text-destructive mt-1">
                  {form.formState.errors.description.message}
                </p>
              )}
            </div>

            {/* TODO: PRICING FOR BETTER TIMES; NOW IT's FREEEEEEE */}
            {/* <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>
                  Pricing <span className="text-destructive">*</span>
                </Label>
                <Link
                  href="/settings/payouts"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-muted-foreground flex gap-2 pb-2"
                >
                  View payouts
                  <svg
                    className="ml-1 h-3 w-3"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M7 17L17 7" />
                    <path d="M7 7h10v10" />
                  </svg>
                </Link>
              </div>
              <div className="border-input relative flex w-full items-start gap-2 rounded-md border p-3 shadow-xs outline-none has-data-[state=checked]:border-ring">
                <Switch
                  id="is-paid"
                  checked={form.watch("is_paid") || false}
                  onCheckedChange={(checked) => {
                    form.setValue("is_paid", checked, { shouldValidate: true })
                    form.setValue("price", checked ? 5 : 0, {
                      shouldValidate: true,
                    })
                  }}
                  className="order-1 h-4 w-6 after:absolute after:inset-0 [&_span]:size-3 data-[state=checked]:[&_span]:translate-x-2 data-[state=checked]:[&_span]:rtl:-translate-x-2"
                />
                <div className="grid grow gap-[4px]">
                  <Label htmlFor="is-paid">
                    Paid Component{" "}
                    <span className="text-xs font-normal leading-[inherit] text-muted-foreground">
                      ($0.70 per unlock)
                    </span>
                  </Label>
                  <p className="text-xs text-muted-foreground">
                    Earn money when others use your component
                  </p>
                </div>
              </div>
            </div> */}
          </div>

          <div
            className={cn(
              "grid gap-4",
              isFirstStep ? "grid-cols-2" : "grid-cols-1",
            )}
          >
          </div>

          {/* <div className="space-y-2">
            <Label htmlFor={websiteId}>Website URL</Label>
            <div className="relative">
              <Input
                type="text"
                id={websiteId}
                value={
                  field.value?.replace(/^(https?:\/\/)+(www\.)?/, "") || ""
                }
                onChange={(e) => field.onChange(e)}
                placeholder="your-website.com"
                className="w-full peer ps-16"
              />
              <span className="pointer-events-none absolute inset-y-0 start-0 flex items-center justify-center ps-3 text-sm text-muted-foreground peer-disabled:opacity-50">
                https://
              </span>
            </div>
            {form.formState.errors.website_url ? (
              <p
                className="text-xs text-destructive"
                role="region"
                aria-live="polite"
              >
                {form.formState.errors.website_url.message}
              </p>
            ) : (
              <p
                className="text-xs text-muted-foreground"
                role="region"
                aria-live="polite"
              >
                Link to your component's documentation or demo
              </p>
            )}
          </div> */}
        </div>
      )}
    </div>
  )
}
