import {
  AlertCircle,
  AlignLeft,
  AppWindow,
  BadgeCheck,
  BarChart2,
  BarChart3,
  Bell,
  BellRing,
  Bookmark,
  Bot,
  Calendar,
  CalendarDays,
  CheckSquare,
  ChevronDown,
  ChevronDownSquare,
  ChevronsLeftRight,
  CircleDot,
  CircleDollarSign,
  CircleUser,
  Clock,
  Compass,
  Component,
  CreditCard,
  Crown,
  Dock,
  FileText,
  FolderGit2,
  FolderTree,
  GalleryHorizontal,
  GitCompare,
  Globe,
  Group,
  Hash,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Inbox,
  Info,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Link2,
  List,
  ListCollapse,
  ListOrdered,
  Loader2,
  LogIn,
  MapPin,
  Megaphone,
  Menu,
  MessageSquare,
  MoreHorizontal,
  MousePointer,
  MousePointerClick,
  Package,
  Palette,
  PanelBottom,
  PanelLeft,
  Quote,
  Shapes,
  Sliders,
  SlidersHorizontal,
  Sparkles,
  Square,
  Table,
  Tag,
  TextCursorInput,
  ToggleLeft,
  Type,
  UploadCloud,
  UserCheck,
  UserPlus,
  Users,
  Video,
  Wand2,
  Workflow,
} from "lucide-react"

export type MainNavigationItem = {
  title: string
  value: string
  icon: any
  isNew?: boolean
  subitems?: {
    title: string
    href: string
    externalLink?: boolean
    isNew?: boolean
  }[]
}

export const mainNavigationItems: MainNavigationItem[] = [
  {
    title: "Home",
    value: "home",
    icon: Home,
  },
  {
    title: "Components",
    value: "components",
    icon: Component,
  },
  {
    title: "Bundles",
    value: "bundles",
    icon: Package,
  },
  {
    title: "Templates",
    value: "templates",
    icon: Layers,
  },
  {
    title: "Creators",
    value: "authors",
    icon: Users,
  },
  {
    title: "Premium Stores",
    value: "pro",
    icon: Crown,
  },
  {
    title: "Collections",
    value: "collections",
    icon: Bookmark,
  },
]

// This is a separate navigation item for AI Component Builder that will only be used for the sidebar
// and won't be part of the tab navigation
export const magicNavItem = {
  title: "AI UI Builder",
  icon: Wand2,
  subitems: [
    {
      title: "Magic Chat Waitlist",
      href: "/magic-chat",
      isNew: true,
    },
    {
      title: "Magic MCP",
      href: "/magic",
      externalLink: true,
    },
    {
      title: "Onboarding",
      href: "/magic/onboarding",
    },
    {
      title: "Console",
      href: "/magic/console",
    },
    {
      title: "Pricing",
      href: "/pricing",
    },
  ],
}

export type NavigationItem = {
  title: string
  href: string
  isNew?: boolean
  demoId?: number
  demosCount?: number
  externalLink?: boolean
  icon?: any
}

export type NavigationCategory = {
  title: string
  icon: any
  items: NavigationItem[]
  isNew?: boolean
}

export const marketing: NavigationItem[] = [
  {
    title: "Announcements",
    href: "/s/announcement",
    demoId: 541,
    demosCount: 71,
    icon: MessageSquare,
  },
  {
    title: "ASCII Art",
    href: "/s/ascii",
    isNew: true,
    icon: Hash,
  },
  {
    title: "Backgrounds",
    href: "/s/background",
    demoId: 1120,
    demosCount: 365,
    icon: ImageIcon,
  },
  {
    title: "Borders",
    href: "/s/border",
    demoId: 1135,
    demosCount: 111,
    icon: Square,
  },
  {
    title: "Calls to Action",
    href: "/s/call-to-action",
    demoId: 1379,
    demosCount: 501,
    icon: Megaphone,
  },
  {
    title: "Clients",
    href: "/s/clients",
    demoId: 981,
    demosCount: 17,
    icon: UserCheck,
  },
  {
    title: "Comparisons",
    href: "/s/comparison",
    demoId: 1466,
    demosCount: 31,
    icon: GitCompare,
  },
  {
    title: "Docks",
    href: "/s/dock",
    demoId: 990,
    demosCount: 49,
    icon: Dock,
  },
  {
    title: "FAQs",
    href: "/s/faq",
    demosCount: 191,
    icon: HelpCircle,
  },
  {
    title: "Features",
    href: "/s/features",
    demoId: 1521,
    demosCount: 318,
    icon: Sparkles,
  },
  {
    title: "Footers",
    href: "/s/footer",
    demoId: 1520,
    demosCount: 65,
    icon: PanelBottom,
  },
  {
    title: "Galleries",
    href: "/s/gallery",
    demosCount: 272,
    icon: LayoutGrid,
  },
  {
    title: "Gradients",
    href: "/s/gradients",
    isNew: true,
    icon: Palette,
  },
  {
    title: "Heroes",
    href: "/s/hero",
    demoId: 1526,
    demosCount: 1152,
    icon: LayoutTemplate,
  },
  {
    title: "Hooks",
    href: "/s/hook",
    demoId: 915,
    demosCount: 51,
    icon: Workflow,
  },
  {
    title: "Images",
    href: "/s/image",
    demoId: 1018,
    demosCount: 428,
    icon: ImageIcon,
  },
  {
    title: "Maps",
    href: "/s/map",
    demoId: 999,
    demosCount: 51,
    icon: MapPin,
  },
  {
    title: "Marquees",
    href: "/s/marquee",
    demosCount: 113,
    icon: GalleryHorizontal,
  },
  {
    title: "Navigation Menus",
    href: "/s/navbar-navigation",
    demoId: 1432,
    demosCount: 477,
    icon: Menu,
  },
  {
    title: "Pricing Sections",
    href: "/s/pricing-section",
    demoId: 1511,
    demosCount: 216,
    icon: CircleDollarSign,
  },
  {
    title: "Scroll Areas",
    href: "/s/scroll-area",
    demoId: 857,
    demosCount: 293,
    icon: MousePointer,
  },
  {
    title: "Shaders",
    href: "/s/shaders",
    isNew: true,
    icon: Layers,
  },
  {
    title: "Stats & KPIs",
    href: "/s/stats-kpi",
    demosCount: 153,
    icon: BarChart3,
  },
  {
    title: "Steppers",
    href: "/s/stepper",
    demosCount: 124,
    icon: ListOrdered,
  },
  {
    title: "Team Sections",
    href: "/s/team-section",
    demosCount: 119,
    icon: Users,
  },
  {
    title: "Testimonials",
    href: "/s/testimonials",
    demoId: 822,
    demosCount: 161,
    icon: Quote,
  },
  {
    title: "Texts",
    href: "/s/text",
    demoId: 1515,
    demosCount: 663,
    icon: Type,
  },
  {
    title: "Timelines",
    href: "/s/timeline",
    demosCount: 74,
    icon: Clock,
  },
  {
    title: "Videos",
    href: "/s/video",
    demoId: 651,
    demosCount: 162,
    icon: Video,
  },
].sort((a, b) => a.title.localeCompare(b.title))

export const ui: NavigationItem[] = [
  {
    title: "Accordions",
    href: "/s/accordion",
    demoId: 1517,
    demosCount: 234,
    icon: ListCollapse,
  },
  {
    title: "AI Chats",
    href: "/s/ai-chat",
    isNew: true,
    demoId: 1437,
    demosCount: 248,
    icon: Bot,
  },
  {
    title: "Alerts",
    href: "/s/alert",
    demoId: 341,
    demosCount: 240,
    icon: AlertCircle,
  },
  {
    title: "Avatars",
    href: "/s/avatar",
    demoId: 791,
    demosCount: 597,
    icon: CircleUser,
  },
  {
    title: "Badges",
    href: "/s/badge",
    demoId: 513,
    demosCount: 605,
    icon: BadgeCheck,
  },
  {
    title: "Buttons",
    href: "/s/button",
    demoId: 1346,
    demosCount: 2043,
    icon: MousePointerClick,
  },
  {
    title: "Calendars",
    href: "/s/calendar",
    isNew: true,
    demoId: 461,
    demosCount: 239,
    icon: Calendar,
  },
  {
    title: "Cards",
    href: "/s/card",
    demoId: 858,
    demosCount: 1780,
    icon: CreditCard,
  },
  {
    title: "Carousels",
    href: "/s/carousel",
    demoId: 1247,
    demosCount: 239,
    icon: SlidersHorizontal,
  },
  {
    title: "Charts & Data Viz",
    href: "/s/charts",
    demosCount: 246,
    icon: BarChart2,
  },
  {
    title: "Checkboxes",
    href: "/s/checkbox",
    demoId: 90,
    demosCount: 238,
    icon: CheckSquare,
  },
  {
    title: "Cursors",
    href: "/s/cursor",
    demosCount: 152,
    icon: MousePointer,
  },
  {
    title: "Dashboards",
    href: "/s/dashboard",
    demosCount: 400,
    icon: LayoutDashboard,
  },
  {
    title: "Date Pickers",
    href: "/s/date-picker",
    isNew: true,
    demoId: 169,
    demosCount: 250,
    icon: CalendarDays,
  },
  {
    title: "Dialogs / Modals",
    href: "/s/modal-dialog",
    demoId: 1462,
    demosCount: 328,
    icon: AppWindow,
  },
  {
    title: "Dropdowns",
    href: "/s/dropdown",
    demoId: 390,
    demosCount: 506,
    icon: ChevronDown,
  },
  {
    title: "Empty States",
    href: "/s/empty-state",
    demoId: 1435,
    demosCount: 77,
    icon: Inbox,
  },
  {
    title: "File Trees",
    href: "/s/file-tree",
    demoId: 1223,
    demosCount: 61,
    icon: FolderTree,
  },
  {
    title: "File Uploads",
    href: "/s/upload-download",
    demoId: 377,
    demosCount: 154,
    icon: UploadCloud,
  },
  {
    title: "Forms",
    href: "/s/form",
    isNew: true,
    demoId: 918,
    demosCount: 1522,
    icon: FileText,
  },
  {
    title: "Globes",
    href: "/s/globe",
    demosCount: 41,
    icon: Globe,
  },
  {
    title: "Grids & Bento",
    href: "/s/bento-grid",
    demosCount: 620,
    icon: LayoutGrid,
  },
  {
    title: "Icons",
    href: "/s/icons",
    demoId: 865,
    demosCount: 851,
    icon: Shapes,
  },
  {
    title: "Inputs",
    href: "/s/input",
    demoId: 1456,
    demosCount: 949,
    icon: TextCursorInput,
  },
  {
    title: "Links",
    href: "/s/link",
    demoId: 1287,
    demosCount: 354,
    icon: Link2,
  },
  {
    title: "Lists",
    href: "/s/list",
    demosCount: 349,
    icon: List,
  },
  {
    title: "Menus",
    href: "/s/menu",
    demoId: 1428,
    demosCount: 287,
    icon: MoreHorizontal,
  },
  {
    title: "Notifications",
    href: "/s/notification",
    isNew: true,
    demoId: 400,
    demosCount: 247,
    icon: BellRing,
  },
  {
    title: "Numbers",
    href: "/s/number",
    demoId: 1444,
    demosCount: 54,
    icon: Hash,
  },
  {
    title: "Onboarding",
    href: "/s/onboarding",
    demosCount: 53,
    icon: Compass,
  },
  {
    title: "Paginations",
    href: "/s/pagination",
    demoId: 453,
    demosCount: 130,
    icon: ChevronsLeftRight,
  },
  {
    title: "Popovers",
    href: "/s/popover",
    isNew: true,
    demoId: 403,
    demosCount: 179,
    icon: MessageSquare,
  },
  {
    title: "Radio Groups",
    href: "/s/radio-group",
    demoId: 1410,
    demosCount: 22,
    icon: CircleDot,
  },
  {
    title: "Sidebars",
    href: "/s/sidebar",
    demoId: 1075,
    demosCount: 10,
    icon: PanelLeft,
  },
  {
    title: "Sign Ins",
    href: "/s/sign-in",
    demoId: 374,
    demosCount: 4,
    icon: LogIn,
  },
  {
    title: "Sign ups",
    href: "/s/registration-signup",
    demoId: 373,
    demosCount: 4,
    icon: UserPlus,
  },
  {
    title: "Selects",
    href: "/s/select",
    demoId: 289,
    demosCount: 62,
    icon: ChevronDownSquare,
  },
  {
    title: "Sliders",
    href: "/s/slider",
    demoId: 329,
    demosCount: 45,
    icon: Sliders,
  },
  {
    title: "Spinner Loaders",
    href: "/s/spinner-loader",
    isNew: true,
    demoId: 523,
    demosCount: 21,
    icon: Loader2,
  },
  {
    title: "Tables",
    href: "/s/table",
    demoId: 105,
    demosCount: 30,
    icon: Table,
  },
  {
    title: "Tags",
    href: "/s/chip-tag",
    demoId: 1285,
    demosCount: 6,
    icon: Tag,
  },
  {
    title: "Tabs",
    href: "/s/tabs",
    demoId: 635,
    demosCount: 38,
    icon: FolderGit2,
  },
  {
    title: "Text Areas",
    href: "/s/textarea",
    demoId: 190,
    demosCount: 22,
    icon: AlignLeft,
  },
  {
    title: "Toasts",
    href: "/s/toast",
    demoId: 573,
    demosCount: 2,
    icon: Bell,
  },
  {
    title: "Toggles",
    href: "/s/toggle",
    demoId: 250,
    demosCount: 12,
    icon: ToggleLeft,
  },
  {
    title: "Tooltips",
    href: "/s/tooltip",
    demoId: 230,
    demosCount: 28,
    icon: Info,
  },
].sort((a, b) => a.title.localeCompare(b.title))

export const categories: NavigationCategory[] = [
  {
    title: "Marketing Blocks",
    icon: Dock,
    items: marketing,
  },
  {
    title: "UI Components",
    icon: Group,
    items: ui,
  },
]
